# Site settings
title: "Məhərrəmovun bloqu"
author: "Şamxal Məhərrəmov"
description: "Full-Stack Developer və Həvəskar Game developer olaraq öz təcrübələrimi, həllərimi bölüşəcəyim bir bloq"
keywords: "Proqramlaşdırma öyrən, Oyun yaratmaq, Sayt yaratmaq, Laravel öyrən, Javascript öyrən"
biography: "10+ il təcrübəsi olan bir Full-Stack Developerəm. Xüsusilə CRM, ERP, Mühasibatlıq/Maliyyə, Sənəd dövriyyəsi tipli layihələr üzrə böyük praktikam var. Bir neçə dövlət əhəmiyyətli layihələrin müəllifiyəm."
colophon: "© 2020 by Shamkhal Maharramov."

baseurl: ""
url: "https://maharramoff.github.io"

github_username: maharramoff
linkedin_username: shamkhal
facebook_username: m.samxal

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
