# Site settings
title: "On Software Engineering, Mathematics<br>and Philosophy"
author: "Shamkhal Maharramov"
description: "This is a blog about software and the occasional philosophy."
keywords: "Software Engineering, Mathematics, Philosophy, Scala, Epistemology, Existentialism, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability, Puzzles"
biography: "I am Senior Full-Stack Developer with 10+ years of hands-on experience in Design, Development and Deployment of web applicaধons using various technologies."
colophon: "© 2018 by Shamkhal Maharramov.<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> unless otherwise noted"

baseurl: ""
url: "http://hugosereno.eu"

github_username: maharramoff
linkedin_username: shamkhal
facebook_username: m.samxal

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
